NDefines.NDiplomacy.MIN_RELATIONS_TO_ALLY = -200
NDefines.NDiplomacy.MIN_RELATIONS_TO_SUPPORT_INDEPENDENCE = -200
NDefines.NCountry.MAXIMUM_CONDOTTIERI = 100
NDefines.NDiplomacy.CHANGE_RIVAL_YEARS = 10