NDefines.NDiplomacy.MIN_RELATIONS_TO_ALLY = -200
NDefines.NDiplomacy.MIN_RELATIONS_TO_SUPPORT_INDEPENDENCE = -200
NDefines.NMilitary.CONDOTTIERI_MAX_ARMIES_PER_COUNTRY = 3
NDefines.NDiplomacy.CONDOTTIERI_RENT_ONLY_WHEN_INSUFFICIENT_MONEY = false
